version: '3.8'

services:
  app:
    build: .
    ports:
      - "9010:9010"
    environment:
      - mongo_user=root
      - mongo_password=rootuser
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootuser

volumes:
  mongo_data: {}