version: '3.8'

services:
  app:
    build: .
    ports: 
      - "9010:9010"
    environment:
      DB_URL: "postgres://go_server:MySecretPass@postgresql_db:5432/stocks_db?sslmode=disable"
    depends_on:
      - postgresql_db

  postgresql_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: go_server
      POSTGRES_PASSWORD: MySecretPass
      POSTGRES_DB: stocks_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: